FROM node:buster-slim
ARG DEBIAN_FRONTEND=noninteractive
ENV DISPLAY=:99
ENV CI=1
ENV QT_X11_NO_MITSHM=1
ENV _X11_NO_MITSHM=1
ENV _MITSHM=0
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1
COPY entrypoint.sh /e2e/entrypoint.sh
WORKDIR /e2e
RUN chmod +x entrypoint.sh
RUN apt-get -y update && apt-get install -yq --no-install-recommends libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb procps
RUN npm install -g cypress


